### PR TITLE
Build imported static libSOIL part together with add-on

### PR DESCRIPTION
**Pull request by AlwinEsch**
This change include the needed static library part to add-on itself.

One point for them is to fix the Jenkins add-on build, which was all the time failed for me.
The other is to make it Linux Distribution independent.
And the last for me was that the code is very small and the related Makefile's from original are a bit stu..d.

Has seen on https://github.com/xbmc/repo-binary-addons/blob/master/screensaver.matrixtrails/platforms.txt that is limited to Linux, is this right? On Readme it means "On linux, you have to provide the libSOIL library. Debian/Ubuntu: sudo apt-get install libsoil-dev" and not sure if somewhere else, maybe also with this change possible for others.

### CODE REVIEW

**Comment by notspiff** [comment]
@wsnipex your call soil will be needed by more addons eventually.

It is linux only in the sense that it is opengl only and i care more about the muck under my nails than i care for that prioprietary pos that is osx.

**Comment by wsnipex** [comment]
imho it'd be much better to add it to depends instead of directly including it. If other addons will need soil, we will have to do it properly anyway.

**Comment by notspiff** [comment]
that's what i figured as well.

**Comment by AlwinEsch** [comment]
No problem I change it then over to a normal build of them. Is it OK to add http://archive.ubuntu.com/ubuntu/pool/universe/libs/libsoil/libsoil_1.07~20080707.dfsg.orig.tar.gz renamed to Kodi storage? To have name compatible with extracted folder (libsoil-1.07~20080707.dfsg)

**Comment by wsnipex** [comment]
we don't need to care about the folder name. Linux usually won't use the depends here anyway, as you'd just install the package. I'd go with upstream soil tarball.

**Comment by AlwinEsch** [comment]
Have temporary committed the renamed source package from http://packages.ubuntu.com/trusty/libsoil-dev can this loaded up to http://mirrors.xbmc.org/build-deps/sources/?

**Comment by AlwinEsch** [comment]
So is updated again, it use the Download URL direct from Ubuntu.

Tested the build on following conditions:
 - Single build with lib installed and without:
  ```
mkdir build
cd build
cmake ..
make
```
Without them installed was it automatically created.

Also checked the jenkins build way, which was also ok here.

Further has I added a .gitignore (has one time wrongly added the build folder) and the README.md.

**Comment by notspiff** [comment]
All other depends are static. Is there a reason to do otherwise here?

**Comment by AlwinEsch** [comment]
Is static used, only the build create also the not needed shared.

**Comment by notspiff** [comment]
Right. @wsnipex is the external depends url acceptable?
15. okt. 2015 20:36 skrev "Alwin Esch" <notifications@github.com>:

**Comment by AlwinEsch** [comment]
```
ldd screensaver.matrixtrails.so.1.0.0
	linux-vdso.so.1 =>  (0x00007fff29078000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f78f89d4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f78f86cc000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f78f84b6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f78f80ec000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f78f8f02000)
```

**Comment by notspiff** [comment]
Meh. It is an improvement in any case and can easily be changed. Thanks alwin.

**Pull request merged**
